['AAAAAAAAAAAAAAAAAAAAAAAT-AAAAAAAAAAAAAA---------',
'-AAAAAAAAAAAAAAAAAAAACA--AAAAAAAAAAAAAAAAAAAAAAA', 
'--AAAAAAAAAAAAAAAAAAAAAAATTAAAAAAAAAAAAAAAAAAAAAAA', 
'--AAAAAAAAAAAAAAAAAAAAAAACGAAAAAAAAAAAAAAAAAAAAAAA', 
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA']